name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
version-template: "v$MAJOR.$MINOR.$PATCH"
change-template: "- #$NUMBER $TITLE (@$AUTHOR)"
template: |
  ## Change Log
  $CHANGES
  ## Contributors
  $CONTRIBUTORS
